version: "2"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53/tcp
      - 53/udp
      - 80/tcp
    environment:
      - FTLCONF_LOCAL_IPV4=192.168.50.22
      - WEBPASSWORD= #password here
      - PIHOLE_DNS_=192.168.50.23
      - TZ=America/Sao_Paulo
      - DNSMASQ_USER=root
      - DNSMASQ_LISTENING=local
    volumes:
      - /volume1/docker/pihole-unbound/pihole:/etc/pihole:rw
      - /volume1/docker/pihole-unbound/dnsmasq.d:/etc/dnsmasq.d/:rw
    networks:
      macvlan:
        ipv4_address: 192.168.50.22
      bridge:
        ipv4_address: 192.168.22.2
    restart: always
  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    ports:
      - 53/tcp
      - 53/udp
    networks:
      macvlan:
        ipv4_address: 192.168.50.23
    restart: always

networks:
  macvlan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.50.0/24
          gateway: 192.168.50.1
          ip_range: 192.168.50.22/30
  bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.22.0/24
          gateway: 192.168.22.1
          ip_range: 192.168.22.2/32
