version: '3.3'
services:
  speedtest-tracker:
    container_name: speedtest-tracker
    image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
    ports:
      - '8811:80'
      - '8822:443'
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Sao_Paulo
    volumes:
      - '/volume1/docker/speedtest-tracker:/config'
      - '/volume1/docker/speedtest-tracker/web:/etc/ssl/web'
    restart: unless-stopped