version: "3"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1026 #Change this to your UID
      - PGID=100 #Change this to your GID
      - TZ=America/Sao_Paulo
    volumes:
      - /volume1/docker/jellyfin/config:/config #Mount your config directory here
      - /volume1/docker/jellyfin/cache:/cache #Mount your config directory here
      - /volume1/docker/jellyfin/transcodes:/transcodes #Mount your config directory here
      - /volume1/Media/Séries:/data/tvshows #Mount TVShows here
      - /volume1/Media/Filmes:/data/movies #Mount Movies here
      - /volume1/Media/Cursos:/data/cursos
    devices:
      # VA-API devices
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - 8096:8096
    restart: unless-stopped
