version: '3'
services:
  sonarcube:
    image: sonarqube:9.9.1-community
    container_name: sonarqube
    environment:
      SONAR_SEARCH_JAVAADDITIONALOPTS: "-Dbootstrap.system_call_filter=false"
      SONAR_JDBC_URL: jdbc:postgresql://192.168.50.20:5454/sonarqube
      SONAR_JDBC_USERNAME: admin-sonar
      SONAR_JDBC_PASSWORD: password-sonar
    volumes:
      # - sonarqube_data:/opt/sonarqube/data
      # - sonarqube_extensions:/opt/sonarqube/extensions
      # - sonarqube_logs:/opt/sonarqube/logs
      - /volume1/docker/sonarqube/data:/opt/sonarqube/data
      - /volume1/docker/sonarqube/extensions:/opt/sonarqube/extensions
      - /volume1/docker/sonarqube/logs:/opt/sonarqube/logs
    ports:
      - 9999:9000
    networks:
      - network-sonarqube
networks:
  network-sonarqube:
    name: development
# volumes:
#   sonarqube_data:
#   sonarqube_extensions:
#   sonarqube_logs: