version: '3.8'
services:
  postgres:
    image: postgres:14.8-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Sao_Paulo
      - POSTGRES_USER=admin-postgres
      - POSTGRES_PASSWORD=password-postgres
    ports:
      - 5454:5432
    volumes: 
      - /volume1/docker/postgres:/var/lib/postgresql/data
    networks:
      - network-postgres
networks:
  network-postgres:
    name: development